# Generated by Django 2.2.4 on 2019-08-21 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='passenger',
        ),
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flights.Flight'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='flights.Seat'),
        ),
    ]
